# Generated by Django 3.2.5 on 2022-03-16 03:16
import logging

from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.utils import ProgrammingError

logger = logging.getLogger()  # root logger


def compute_search_vector(apps, schema_editor):
    logger.info("\nUpdating current messages")
    message = apps.get_model("rfis", "Message")
    message.objects.update(vector_body_column=SearchVector("debug_unparsed_body"))
    logger.info("\nSuccessfully updated current messages")


class Migration(migrations.Migration):

    dependencies = [
        ("rfis", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger
                ON rfis_message;

                CREATE TRIGGER search_vector_trigger
                BEFORE INSERT OR UPDATE OF debug_unparsed_body, vector_body_column
                ON rfis_message
                FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(
                vector_body_column, 'pg_catalog.english', debug_unparsed_body
                );

                UPDATE rfis_message SET vector_body_column = NULL;
                """,
            # when the migration is unapplied
            reverse_sql=""" 
                DROP TRIGGER IF EXISTS search_vector_trigger
                ON rfis_message;
                """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
