# Generated by Django 3.2.5 on 2022-03-17 15:32

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0002_vector_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='vector_body_column',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
