# Generated by Django 3.2.5 on 2022-05-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0003_auto_20220317_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_received']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-time_received']},
        ),
    ]
