# Generated by Django 3.2.14 on 2022-09-11 20:35

from django.db import migrations, models
import rfis.models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0005_auto_20220517_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-time_received']},
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_group',
            field=models.ForeignKey(default=rfis.models.ThreadGroup.get_thread_group_sentinel_id, on_delete=models.SET(rfis.models.ThreadGroup.get_thread_group_sentinel_id), to='rfis.threadgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_topic',
            field=models.ForeignKey(default=rfis.models.ThreadTopic.get_thread_topic_sentinel_id, on_delete=models.SET(rfis.models.ThreadTopic.get_thread_topic_sentinel_id), to='rfis.threadtopic', verbose_name='Topic'),
        ),
    ]
